import { StyleSheet } from "react-native";

import Colors from "../../../../../shared/styles/Colors";

export const styles = StyleSheet.create({
  card: {
    borderRadius: 22,
    backgroundColor: Colors.white,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EAECF0",
    gap: 14,
  },
  header: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: 16,
    fontWeight: "800",
    color: "#101828",
  },
  subtitle: {
    marginTop: 3,
    fontSize: 12,
    color: "#667085",
  },
  totalProgressSection: {
    borderRadius: 16,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EAECF0",
    padding: 12,
    gap: 9,
  },
  totalProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  totalProgressLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#101828",
  },
  totalProgressValue: {
    fontSize: 15,
    fontWeight: "900",
    color: Colors.greenColor,
  },
  totalProgressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#EAECF0",
    overflow: "hidden",
  },
  totalProgressFill: {
    height: "100%",
    borderRadius: 999,
  },
  totalProgressFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  totalProgressMeta: {
    fontSize: 11,
    color: "#667085",
  },
  fieldList: {
    gap: 10,
  },
  fieldCard: {
    borderRadius: 18,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: "#EAECF0",
    borderLeftWidth: 4,
    overflow: "hidden",
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  fieldMain: {
    padding: 13,
    gap: 10,
  },
  fieldTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  fieldNameWrap: {
    flex: 1,
    minWidth: 0,
  },
  fieldName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#101828",
  },
  areaPillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  areaPill: {
    borderRadius: 10,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EAECF0",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  areaPillLabel: {
    fontSize: 9,
    color: "#667085",
    textTransform: "uppercase",
  },
  areaPillValue: {
    marginTop: 1,
    fontSize: 11,
    fontWeight: "800",
    color: "#344054",
  },
  percentBadge: {
    minWidth: 48,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  percentBadgeText: {
    fontSize: 13,
    fontWeight: "900",
  },
  costRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  costChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EAECF0",
    paddingHorizontal: 9,
    paddingVertical: 6,
    maxWidth: "62%",
  },
  costValue: {
    fontSize: 12,
    fontWeight: "800",
    color: "#101828",
  },
  costCaption: {
    fontSize: 11,
    fontWeight: "700",
    color: "#667085",
  },
  progressTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: "#EAECF0",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  details: {
    borderTopWidth: 1,
    borderTopColor: "#EAECF0",
    backgroundColor: "#FCFCFD",
    paddingHorizontal: 13,
    paddingVertical: 10,
    gap: 8,
  },
  metricLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  metricLabel: {
    flex: 1,
    fontSize: 12,
    color: "#667085",
  },
  metricValueWrap: {
    alignItems: "flex-end",
    maxWidth: "56%",
  },
  metricValue: {
    fontSize: 12,
    fontWeight: "700",
    color: "#101828",
  },
  metricCaption: {
    marginTop: 1,
    fontSize: 10,
    color: "#667085",
  },
  showMoreButton: {
    minHeight: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  showMoreText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#667085",
  },
  transferSection: {
    borderRadius: 16,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EAECF0",
    padding: 12,
    gap: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#101828",
    marginBottom: 2,
  },
  emptyText: {
    fontSize: 12,
    color: "#667085",
  },
  techniqueSection: {
    borderRadius: 16,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EAECF0",
    padding: 12,
    gap: 12,
  },
  techniqueList: {
    gap: 10,
  },
  techniqueLoadRow: {
    gap: 6,
  },
  techniqueLoadHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  techniqueName: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: "#344054",
  },
  techniqueLoadValue: {
    fontSize: 12,
    fontWeight: "900",
    color: Colors.greenColor,
  },
  techniqueLoadTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#EAECF0",
    overflow: "hidden",
  },
  techniqueLoadFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: Colors.greenColor,
  },
  techniqueMetricsGrid: {
    gap: 10,
  },
  techniqueMetricCard: {
    borderRadius: 14,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: "#EAECF0",
    padding: 10,
    gap: 8,
  },
  techniqueMetricTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#101828",
  },
  techniqueMetricLine: {
    gap: 2,
  },
  techniqueMetricName: {
    fontSize: 11,
    color: "#667085",
  },
  techniqueMetricValue: {
    fontSize: 15,
    fontWeight: "900",
    color: "#101828",
  },
});
