CREATE TABLE `processedShiftData` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`key` text NOT NULL,
	`work_type` text NOT NULL,
	`production_shift_id` text NOT NULL,
	`shift_type` text,
	`work_place_name` text,
	`work_name` text,
	`agricultural_machinery_name` text,
	`task_field_name` text DEFAULT '' NOT NULL,
	`date` text NOT NULL,
	`open_at` text DEFAULT '' NOT NULL,
	`close_at` text DEFAULT '' NOT NULL,
	`start_at` text DEFAULT '' NOT NULL,
	`end_at` text DEFAULT '' NOT NULL,
	`icon_link` text DEFAULT '' NOT NULL,
	`tariff_value` text DEFAULT '0' NOT NULL,
	`tariff_price` text DEFAULT '0' NOT NULL,
	`tariff_unit` text,
	`unit` text,
	`unit_code` text,
	`tariff_price_unit` text,
	`output_value_area` text DEFAULT '0' NOT NULL,
	`time` real DEFAULT 0 NOT NULL,
	`long_stops` real DEFAULT 0 NOT NULL,
	`small_stops` real DEFAULT 0 NOT NULL,
	`time_string` text DEFAULT '0м' NOT NULL,
	`long_stops_string` text DEFAULT '0м' NOT NULL,
	`small_stops_string` text DEFAULT '0м' NOT NULL,
	`fact_area` text DEFAULT '0' NOT NULL,
	`overtime_bonus` text DEFAULT '0' NOT NULL,
	`experience_bonus` text DEFAULT '0' NOT NULL,
	`norm_value` text,
	`norm_value_ha` text,
	`production_norm_value` text,
	`production_fact_value` text,
	`fuel_norm_value` text,
	`fuel_fact_value` text,
	`max_speed` text DEFAULT '0' NOT NULL,
	`avg_speed` text DEFAULT '0' NOT NULL,
	`terms_max_speed` text,
	`processing_depth` text,
	`solute_flow_rate` text,
	`part_ids` text,
	`part_initial` integer,
	`task_field_id` text DEFAULT '' NOT NULL,
	`tariff_id` text DEFAULT '' NOT NULL,
	`work_place_id` text DEFAULT '' NOT NULL,
	`agricultural_machinery_id` text DEFAULT '' NOT NULL,
	`technique_standard_id` text DEFAULT '' NOT NULL,
	`is_archived` integer DEFAULT false NOT NULL,
	`is_shift_header` integer DEFAULT false NOT NULL
);
