import { ImageSourcePropType } from "react-native";
export interface JsonMap {
  [key: string]: ImageSourcePropType;
}
export const Icons: JsonMap = {
  "arrow-left": require("./ic_arrow_left.png"),
  "arrow-right": require("./ic_arrow_right.png"),
  "arrows-out-simple": require("./ic_arrows_out_simple.png"),
  "arrow-down": require("./ic_arrow_down.png"),
  "arrow-up": require("./ic_arrow_up.png"),
  cardholder: require("./ic_cardholder.png"),
  "caret-double-left": require("./ic_caret_double_left.png"),
  "caret-double-right": require("./ic_caret_double_right.png"),
  "caret-down": require("./ic_caret_down.png"),
  "caret-up": require("./ic_caret_up.png"),
  "caret-left": require("./ic_caret_left.png"),
  "caret-right": require("./ic_caret_right.png"),
  eye: require("./ic_eye.png"),
  "eye-slash": require("./ic_eye_slash.png"),
  visa: require("./ic_visa.png"),
  mastercard: require("./ic_mastercard.png"),
  jcb: require("./ic_jcb.png"),
  discover: require("./ic_discover.png"),
  "american-express": require("./ic_american_express.png"),
  "star-activated": require("./ic_star_activated.png"),
  "star-inactive": require("./ic_star_inactive.png"),
  like: require("./ic_like.png"),
  more: require("./ic_more.png"),
  chart_fill: require("./ic_chart_fill.png"),
  chart: require("./ic_chart.png"),
  home_fill: require("./ic_home_fill.png"),
  home: require("./ic_home.png"),
  person_fill: require("./ic_person_fill.png"),
  person: require("./ic_person.png"),
  wallet_fill: require("./ic_wallet_fill.png"),
  wallet: require("./ic_wallet.png"),
  income: require("./ic_income.png"),
  outcome: require("./ic_outcome.png"),
  bell: require("./ic_bell.png"),
  netflix: require("./ic_netflix.png"),
  turkcell: require("./ic_turkcell.png"),
  qr: require("./ic_qr.png"),
  document: require("./ic_document.png"),
  wallet_send: require("./ic_wallet_send.png"),
  menu: require("./ic_menu.png"),
  box: require("./ic_box.png"),
  filter: require("./ic_filter.png"),
  transfer: require("./ic_transfer.png"),
  bank: require("./ic_bank.png"),
  save_money: require("./ic_save_money.png"),
  medical_report: require("./ic_medical_report.png"),
  family: require("./ic_family.png"),
  delivery: require("./ic_delivery.png"),
  health_watch: require("./ic_health_watch.png"),
  insurance: require("./ic_insurance.png"),
  payment_info: require("./ic_payment_info.png"),
  support: require("./ic_support.png"),
  app_report: require("./ic_app_report.png"),
  exit: require("./ic_exit.png"),
  "password_fill": require("./ic_password_fill.png"),
  "ic_technique": require("./ic_technique.jpg")
};
