import { StyleSheet } from "react-native";

import Colors from "../../shared/styles/Colors";

export const forcedCloseShiftModalStyles = StyleSheet.create({
  root: {
    flex: 1,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.black + "80",
  },
  overlay: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  modal: {
    width: "100%",
    maxWidth: 360,
    maxHeight: "92%",
    borderRadius: 22,
    backgroundColor: Colors.white,
    overflow: "hidden",
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#EAECF0",
  },
  closeButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 2,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F2F4F7",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.icon.warning + "20",
  },
  titleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.black,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 12,
    color: Colors.grey500,
  },
  content: {
    flexShrink: 1,
  },
  contentInner: {
    padding: 16,
    gap: 12,
    paddingBottom: 20,
  },
  fields: {
    gap: 12,
  },
  progressBadge: {
    alignSelf: "flex-start",
    minHeight: 26,
    borderRadius: 13,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: Colors.grey100,
  },
  progressText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: Colors.grey600,
  },
  hint: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    color: Colors.grey600,
  },
  shiftSummary: {
    minHeight: 34,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Colors.grey100,
  },
  shiftLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: Colors.grey500,
  },
  shiftValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: Colors.grey800,
  },
  selectedTime: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.icon.warning + "40",
    backgroundColor: Colors.icon.warning + "12",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  selectedLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: Colors.grey600,
  },
  selectedValue: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: Colors.black,
  },
  changeButton: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  changeButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: Colors.grey700,
  },
  actions: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#EAECF0",
  },
  button: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    backgroundColor: Colors.greenColor,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.white,
  },
});
