import { StyleSheet } from "react-native";

import Colors from "../../shared/styles/Colors";

export const styles = StyleSheet.create({
  loadingStatus: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 14,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.greenColor + "26",
    backgroundColor: Colors.greenColorLight,
  },
  loadingStatusText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    color: Colors.grey700,
  },
  viewPager: {
    flex: 1,
  },
  tabContainer: {
    flex: 1,
    paddingHorizontal: 14,
  },
  listContent: {
    paddingBottom: 100,
    paddingTop: 0,
    paddingHorizontal: 4,
    gap: 16,
  },
  emptyListContent: {
    flexGrow: 1,
  },
  loadingEmptyState: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  loadingEmptyTitle: {
    marginTop: 12,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    color: Colors.grey800,
  },
  emptyState: {
    justifyContent: "center",
    alignItems: "center",
  },
  pendingSection: {
    marginTop: 8,
    marginBottom: 12,
    gap: 12,
  },
  pendingGroup: {
    position: "relative",
    gap: 8,
    paddingVertical: 4,
    paddingRight: 0,
    paddingLeft: 14,
    overflow: "hidden",
  },
  pendingGroupAccent: {
    position: "absolute",
    left: 0,
    top: 4,
    bottom: 14,
    width: 4,
    borderRadius: 4,
    backgroundColor: Colors.icon.warning,
  },
  pendingGroupHeader: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  pendingGroupTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  pendingGroupTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    color: Colors.grey600,
  },
  pendingSyncRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.icon.warning + "22",
    backgroundColor: Colors.white,
  },
  pendingSyncIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.icon.warning + "14",
  },
  pendingSyncInfo: {
    flex: 1,
    minWidth: 0,
  },
  pendingSyncTitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: Colors.grey800,
  },
  pendingSyncButton: {
    flexShrink: 0,
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: Colors.greenColor,
  },
  pendingSyncButtonText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "800",
    color: Colors.white,
  },
  pendingStopButton: {
    flexShrink: 0,
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  pendingClosedBadge: {
    flexShrink: 0,
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: Colors.greenColorLight,
  },
  pendingClosedText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: Colors.success,
  },
  shiftChips: {
    flexDirection: "row",
    gap: 8,
    marginHorizontal: 14,
    marginBottom: 10,
  },
  shiftChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
  },
  shiftChipActive: {
    backgroundColor: "#E8F5E9",
  },
  shiftChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.grey700,
  },
  shiftChipTextActive: {
    color: Colors.greenColor,
  },
});
