import { StyleSheet } from "react-native";

import Colors from "../../../../../shared/styles/Colors";

export const styles = StyleSheet.create({
  card: {
    borderRadius: 22,
    backgroundColor: Colors.white,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EAECF0",
    gap: 12,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  titleWrap: {
    flex: 1,
    minWidth: 0,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  title: {
    fontSize: 16,
    fontWeight: "800",
    color: "#101828",
  },
  countChip: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  countChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#667085",
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  addButton: {
    backgroundColor: Colors.greenColor,
  },
  addMenuWrap: {
    position: "relative",
    zIndex: 20,
  },
  addMenu: {
    position: "absolute",
    top: 44,
    right: 0,
    width: 132,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: Colors.white,
    paddingVertical: 6,
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 6,
  },
  addMenuItem: {
    minHeight: 40,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  addMenuText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#344054",
  },
  loadingBox: {
    minHeight: 82,
    borderRadius: 16,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  emptyBox: {
    minHeight: 96,
    borderRadius: 16,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  emptyText: {
    fontSize: 13,
    color: "#667085",
  },
  groupList: {
    gap: 10,
  },
  dateRangeSwitch: {
    flexDirection: "row",
    borderRadius: 12,
    backgroundColor: "#F2F4F7",
    padding: 3,
    gap: 3,
  },
  dateRangeButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  dateRangeButtonActive: {
    backgroundColor: Colors.white,
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  dateRangeButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#667085",
  },
  dateRangeButtonTextActive: {
    color: "#101828",
  },
  dateGroup: {
    gap: 8,
  },
  dateHeader: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#EAECF0",
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dateHeaderToday: {
    backgroundColor: "#ECFDF3",
    borderColor: "#ABEFC6",
  },
  dateTextWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dateTitle: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#667085",
  },
  dateTitleToday: {
    color: Colors.greenColor,
  },
  todayText: {
    borderRadius: 9,
    overflow: "hidden",
    backgroundColor: "#D1FADF",
    paddingHorizontal: 6,
    paddingVertical: 2,
    fontSize: 10,
    fontWeight: "800",
    color: Colors.greenColor,
  },
  dateMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  employeeChip: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  employeeChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#667085",
  },
  employeeList: {
    gap: 10,
  },
  employeeSection: {
    gap: 8,
  },
  employeeEmptyCard: {
    minHeight: 68,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: "#F9FAFB",
    padding: 12,
    justifyContent: "center",
  },
  employeeEmptyName: {
    fontSize: 13,
    fontWeight: "800",
    color: "#101828",
  },
  employeeWorkList: {
    gap: 8,
  },
  workBlock: {
    overflow: "hidden",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: "#F9FAFB",
    padding: 8,
    gap: 8,
  },
  workBlockBody: {
    gap: 8,
  },
  workBlockHeader: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  workBlockAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  workBlockHeaderContent: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  workBlockEmployeeLine: {
    minHeight: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  workBlockEmployeeName: {
    flexShrink: 1,
    fontSize: 12,
    fontWeight: "900",
    color: "#067647",
  },
  workBlockDivider: {
    fontSize: 10,
    color: "#98A2B3",
  },
  workBlockType: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "700",
    color: "#667085",
  },
  workBlockEquipmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
  },
  workBlockEquipmentChip: {
    maxWidth: "100%",
    minHeight: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    backgroundColor: Colors.white,
    paddingHorizontal: 7,
    paddingVertical: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  workBlockEquipmentText: {
    flexShrink: 1,
    fontSize: 10,
    fontWeight: "700",
    color: "#475467",
  },
  workBlockDeleteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FEF3F2",
    alignItems: "center",
    justifyContent: "center",
  },
  workBlockDeleteButtonDisabled: {
    opacity: 0.45,
  },
  timelineWrap: {
    gap: 6,
  },
  timelineToggle: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  timelineToggleText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    color: "#344054",
  },
  timelineModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  timelineModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.35)",
  },
  timelineModalSheet: {
    maxHeight: "72%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: Colors.white,
    paddingTop: 8,
    overflow: "hidden",
  },
  timelineModalHeader: {
    minHeight: 56,
    borderBottomWidth: 1,
    borderBottomColor: "#EAECF0",
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  timelineModalIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#ECFDF3",
    alignItems: "center",
    justifyContent: "center",
  },
  timelineModalTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: "900",
    color: "#101828",
  },
  timelineModalContent: {
    padding: 16,
  },
  timelineCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: "#F9FAFB",
    padding: 12,
    gap: 10,
  },
  timelineSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  timelineRange: {
    fontSize: 12,
    fontWeight: "800",
    color: "#344054",
  },
  timelineTotal: {
    fontSize: 11,
    fontWeight: "700",
    color: "#667085",
  },
  timelineAxis: {
    position: "relative",
    height: 70,
  },
  timelineTick: {
    position: "absolute",
    top: 6,
    bottom: 10,
    width: 40,
    marginLeft: -20,
    alignItems: "center",
  },
  timelineTickLine: {
    width: 1,
    height: 39,
    backgroundColor: "#EAECF0",
  },
  timelineTickText: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: "600",
    color: "#98A2B3",
  },
  timelineBaseLine: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 27,
    height: 2,
    borderRadius: 1,
    backgroundColor: "#D0D5DD",
  },
  timelineSegmentTouch: {
    position: "absolute",
    top: 19,
    height: 18,
    justifyContent: "center",
  },
  timelineSegmentSelected: {
    transform: [{ scaleY: 1.3 }],
  },
  timelineMoveSegmentTouch: {
    zIndex: 4,
  },
  timelineExtendSegmentTouch: {
    zIndex: 3,
  },
  timelineSegment: {
    width: "100%",
    height: 10,
    minWidth: 3,
    borderRadius: 5,
  },
  timelineWorkSegment: {
    backgroundColor: "#22C55E",
  },
  timelineMoveSegment: {
    borderWidth: 1,
    borderColor: "#0891B2",
    backgroundColor: "#00B8D9",
  },
  timelineGapSegment: {
    height: 1,
    borderTopWidth: 2,
    borderStyle: "dashed",
    borderColor: "#98A2B3",
    borderRadius: 0,
  },
  timelineExtendSegment: {
    height: 10,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#2E90FA",
    backgroundColor: "#D1E9FF",
  },
  timelineBreakInterval: {
    position: "absolute",
    top: 16,
    height: 27,
    minWidth: 8,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: "#D92D20",
    backgroundColor: "rgba(217, 45, 32, 0.12)",
    zIndex: 2,
  },
  timelineBreakBadgeAnchor: {
    position: "absolute",
    top: 0,
    width: 80,
    marginLeft: -40,
    alignItems: "center",
    zIndex: 6,
  },
  timelineBreakBadge: {
    minHeight: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FDA29B",
    backgroundColor: "#FEF3F2",
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  timelineBreakBadgeDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#D92D20",
  },
  timelineBreakBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#B42318",
  },
  timelineLegend: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
  },
  timelineLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  timelineLegendDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  timelineLegendWork: {
    backgroundColor: "#22C55E",
  },
  timelineLegendMove: {
    borderWidth: 1,
    borderColor: "#0891B2",
    backgroundColor: "#00B8D9",
  },
  timelineLegendGap: {
    height: 1,
    borderTopWidth: 2,
    borderStyle: "dashed",
    borderColor: "#98A2B3",
    borderRadius: 0,
  },
  timelineLegendExtend: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#2E90FA",
    backgroundColor: "#D1E9FF",
  },
  timelineLegendBreak: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#D92D20",
  },
  timelineLegendText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#667085",
  },
  timelineTotals: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  timelineBreakChip: {
    borderRadius: 8,
    backgroundColor: "#FEF3F2",
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  timelineBreakText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B42318",
  },
  timelineExtendChip: {
    borderRadius: 8,
    backgroundColor: "#EFF8FF",
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  timelineExtendText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#175CD3",
  },
  timelineNavigatorButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#ABEFC6",
    backgroundColor: "#ECFDF3",
    alignItems: "center",
    justifyContent: "center",
  },
  timelineSelection: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: Colors.white,
    padding: 10,
    gap: 9,
  },
  timelineSelectionTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  timelineSelectionHeadingWrap: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    gap: 3,
  },
  timelineSelectionCounter: {
    fontSize: 10,
    fontWeight: "800",
    color: "#98A2B3",
  },
  timelineSelectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  timelineSelectionDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  timelineSelectionTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: "#344054",
  },
  timelineSelectionDetails: {
    borderRadius: 10,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 9,
    paddingVertical: 7,
    gap: 5,
  },
  timelineSelectionTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  timelineSelectionMeta: {
    flexShrink: 1,
    fontSize: 10,
    fontWeight: "600",
    color: "#667085",
  },
  timelineSelectionDuration: {
    marginLeft: "auto",
    borderRadius: 7,
    backgroundColor: "#F2F4F7",
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  timelineSelectionDurationText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#475467",
  },
  timelineSelectionBreak: {
    fontSize: 10,
    fontWeight: "700",
    color: "#B42318",
  },
  deletingStatus: {
    minHeight: 38,
    marginHorizontal: 10,
    marginBottom: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEF3F2",
  },
  deletingStatusText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.error,
  },
  partActionsContainer: {
    position: "relative",
    backgroundColor: Colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EAECF0",
    overflow: "hidden",
  },
  partActionsTrigger: {
    position: "absolute",
    top: 10,
    right: 8,
    zIndex: 4,
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  partActionsTriggerDisabled: {
    opacity: 0.55,
  },
  partActionsModalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  partActionsModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.38)",
  },
  partActionsDialog: {
    width: "100%",
    maxWidth: 380,
    borderRadius: 22,
    backgroundColor: Colors.white,
    padding: 16,
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 12,
  },
  partActionsHeader: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  partActionsHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  partActionsTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#101828",
  },
  partActionsSubtitle: {
    marginTop: 3,
    fontSize: 12,
    color: "#667085",
  },
  partActionsClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  partActionsList: {
    gap: 8,
    marginTop: 8,
  },
  partActionsRow: {
    minHeight: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  partActionsDeleteRow: {
    borderColor: "#FECDCA",
    backgroundColor: "#FEF3F2",
  },
  partActionsEditIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: "#ECFDF3",
    alignItems: "center",
    justifyContent: "center",
  },
  partActionsDeleteIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: "#FEE4E2",
    alignItems: "center",
    justifyContent: "center",
  },
  partActionsRowText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "800",
    color: "#344054",
  },
  partActionsDeleteText: {
    color: "#B42318",
  },
  compactPartRow: {
    position: "relative",
    minHeight: 136,
    backgroundColor: Colors.white,
    paddingLeft: 14,
  },
  compactInitialPartRow: {
    backgroundColor: "#F6FEF9",
  },
  compactSuccessStripe: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: Colors.greenColor,
  },
  compactInfoStripe: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: Colors.blue,
  },
  compactStartBadge: {
    overflow: "hidden",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: "#D1FADF",
    fontSize: 10,
    fontWeight: "800",
    color: Colors.greenColor,
  },
  compactMainWrap: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingRight: 10,
  },
  compactHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingRight: 38,
  },
  compactWorkIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECFDF3",
  },
  compactTransportIcon: {
    backgroundColor: "#EFF8FF",
  },
  compactHeadingWrap: {
    flex: 1,
    minWidth: 0,
  },
  compactTitle: {
    minWidth: 0,
    fontSize: 13,
    fontWeight: "800",
    color: "#101828",
  },
  compactEmployeeText: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "600",
    color: "#667085",
  },
  compactSubtitle: {
    marginTop: 8,
    fontSize: 11,
    color: "#667085",
  },
  compactMetaRow: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 5,
  },
  compactMetaChip: {
    maxWidth: "100%",
    minHeight: 26,
    borderRadius: 8,
    backgroundColor: "#F2F4F7",
    paddingHorizontal: 7,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  compactMetaText: {
    flexShrink: 1,
    fontSize: 10,
    fontWeight: "700",
    color: "#475467",
  },
  compactDayChip: {
    backgroundColor: "#FEF3C7",
  },
  compactNightChip: {
    backgroundColor: "#E0EAFF",
  },
  compactDangerChip: {
    backgroundColor: "#FEF3F2",
  },
  compactInfoChip: {
    backgroundColor: "#EFF8FF",
  },
  compactSourceQrChip: {
    backgroundColor: "#ECFDF3",
    borderWidth: 1,
    borderColor: "#ABEFC6",
  },
  compactSourceManualChip: {
    backgroundColor: "#FFFAEB",
    borderWidth: 1,
    borderColor: "#FEDF89",
  },
  compactSourceAutoChip: {
    backgroundColor: "#F4F3FF",
    borderWidth: 1,
    borderColor: "#D9D6FE",
  },
  compactCorrectionChip: {
    backgroundColor: "#FFFAEB",
    borderWidth: 1,
    borderColor: "#FEDF89",
  },
  compactDayText: {
    color: "#B54708",
  },
  compactNightText: {
    color: "#3538CD",
  },
  compactDangerText: {
    color: "#B42318",
  },
  compactInfoText: {
    color: "#175CD3",
  },
  compactSourceQrText: {
    color: "#067647",
  },
  compactSourceManualText: {
    color: "#B54708",
  },
  compactSourceAutoText: {
    color: "#5925DC",
  },
  compactCorrectionText: {
    color: "#B54708",
  },
  compactMetrics: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
  },
  compactMetric: {
    width: "48%",
    minWidth: 0,
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: "#F2F4F7",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  compactMetricPayment: {
    backgroundColor: "#ECFDF3",
  },
  compactMetricWarning: {
    backgroundColor: "#FFFAEB",
    borderWidth: 1,
    borderColor: "#FEC84B",
  },
  compactMetricLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: "#667085",
  },
  compactMetricValue: {
    marginTop: 1,
    fontSize: 12,
    fontWeight: "900",
    color: "#101828",
  },
  compactMetricMoney: {
    marginTop: 1,
    fontSize: 12,
    fontWeight: "900",
    color: Colors.greenColor,
  },
  compactMetricWarningText: {
    color: "#B54708",
  },
  detailsOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  detailsBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.35)",
  },
  detailsSheet: {
    maxHeight: "94%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: Colors.white,
    paddingTop: 8,
    overflow: "hidden",
  },
  detailsHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D0D5DD",
    marginBottom: 10,
  },
  detailsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#EAECF0",
  },
  detailsShiftBadge: {
    maxWidth: 136,
    minHeight: 32,
    borderRadius: 16,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  detailsShiftBadgeDay: {
    backgroundColor: "#FEF3C7",
  },
  detailsShiftBadgeNight: {
    backgroundColor: "#E0EAFF",
  },
  detailsShiftBadgeText: {
    fontSize: 11,
    fontWeight: "900",
  },
  detailsShiftBadgeTextDay: {
    color: "#B54708",
  },
  detailsShiftBadgeTextNight: {
    color: "#3538CD",
  },
  detailsIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  detailsTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  detailsTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#101828",
  },
  detailsSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: "#667085",
  },
  detailsCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  detailsScroll: {
    maxHeight: 650,
    flexShrink: 1,
  },
  detailsContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 14,
  },
  miniMapCard: {
    gap: 10,
  },
  miniMapHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  miniMapMeta: {
    fontSize: 11,
    fontWeight: "800",
    color: "#667085",
  },
  miniMapFrame: {
    height: 240,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EAECF0",
    overflow: "hidden",
    backgroundColor: "#F2F4F7",
  },
  miniMap: {
    flex: 1,
  },
  miniMapState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  miniMapStateText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#667085",
  },
  detailsSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detailsSummaryItem: {
    width: "48%",
    minHeight: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: "#F9FAFB",
    padding: 12,
    justifyContent: "space-between",
  },
  detailsSummaryLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#667085",
  },
  detailsSummaryValue: {
    marginTop: 6,
    fontSize: 15,
    fontWeight: "900",
    color: "#101828",
  },
  detailsSectionCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EAECF0",
    backgroundColor: Colors.white,
    padding: 12,
    gap: 10,
  },
  detailsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailsSectionIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  detailsSectionTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "900",
    color: "#101828",
  },
  detailsRows: {
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    overflow: "hidden",
  },
  detailsRow: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F2F4F7",
  },
  detailsRowLabel: {
    flex: 0.9,
    fontSize: 12,
    color: "#667085",
  },
  detailsRowValue: {
    flex: 1.2,
    textAlign: "right",
    fontSize: 12,
    fontWeight: "700",
    color: "#101828",
  },
  detailsRowValueStrong: {
    fontWeight: "900",
    color: Colors.greenColor,
  },
  detailsMetricGroups: {
    gap: 10,
  },
  detailsMetricGroup: {
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    padding: 10,
    gap: 8,
  },
  detailsMetricGroupTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#667085",
  },
  detailsItemsList: {
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    padding: 12,
    gap: 8,
  },
  detailsMaterial: {
    fontSize: 12,
    color: "#667085",
  },
  detailsMaterialGroups: {
    gap: 10,
  },
  detailsMaterialGroup: {
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    padding: 10,
    gap: 10,
  },
  detailsMaterialGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailsMaterialGroupIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  detailsMaterialGroupTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontWeight: "900",
    color: "#101828",
  },
  detailsMaterialEmptyText: {
    fontSize: 12,
    color: "#667085",
  },
  noPartsText: {
    paddingVertical: 14,
    textAlign: "center",
    fontSize: 13,
    color: "#667085",
  },
});
